/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  important: true,
  theme: {
    extend: {
      backgroundImage: {
        "home-wave-1": "url('/home-wave-1.svg')",
        "home-wave-1-dark": "url('/home-wave-1-dark.svg')",
        "home-wave-2": "url('/home-wave-2.svg')",
        "home-wave-2-dark": "url('/home-wave-2-dark.svg')",
        "home-wave-3": "url('/home-wave-3.svg')",
        "home-wave-3-dark": "url('/home-wave-3-dark.svg')",
        "home-juice-splash": "url('/home-juice-splash.svg')",
        "swap-cloud": "url('/bg-cloud.svg')",
        "swap-cloud-dark": "url('/bg-cloud-dark.svg')",
        "farm-wave": "url('/farm-wave.svg')",
        "farm-wave-dark": "url('/farm-wave-dark.svg')",
      },
      colors: {
        "leemon-yellow": "#FFFF51",
        "leemon-green": "#44D970",
        "leemon-green2": "#9DFC28",
        "leemon-green3": "#8AFC2C",
        "leemon-green4": "#27AE60",
        "leemon-green-light": "#E8FBFF",
        "leemon-green-light2": "#B5FB23",
        "leemon-green-light3": "#B1FB23",
        "leemon-purple": "#633BB3",
        "leemon-purple2": "#814DE9",
        "leemon-purple-light": "#7435D8",
        "leemon-purple-light2": "#A980FA",
        "leemon-purple-mid": "#4D24A2",
        "leemon-purple-mid2": "#6323BB",
        "leemon-purple-dark": "#39146E",
        "leemon-purple-dark2": "#401484",
        "leemon-purple-dark3": "#1A043A",
        "leemon-purple-dark4": "#230C46",
        "leemon-purple-dark5": "#11002C",
        "leemon-gray-light": "#FAFAFA",
        "leemon-gray-light2": "#EFEAF7",
        "leemon-gray-light3": "#E0E0E0",
        "leemon-gray-light4": "#F7F7F7",
        "leemon-gray-light-5": "#5B5B5B",
        "leemon-red": "#E40060",
      },
      dropShadow: {
        shape: "8px 8px 0 #39146E",
        shape2: "10px 12px 0 #39146E",
        shapeDeep: "17px 20px 0 #39146E",
        button: "5.3px 5.8px 0 #39146E",
        buttonLight: "3px 3px 0 #7435D8",
        buttonDeep: "7.3px 8.8px 0 #39146E",
        buttonDeepLight: "5px 5px 0 #7435D8",
        buttonWhite: "5.3px 5.8px 0 #FFFFFF",
        buttonDeepWhite: "7.3px 8.8px 0 #FFFFFF",
        input: "4px 4px 0 #7435D8",
        tooltip: "0px 2px 0 #44D970",
        "tooltip-top": "0px -2px 0 #44D970",
        "shape-light": "5.3px 5.8px 0 #6323BB",
        "shape-dark": "5.3px 5.8px 0 #11002C",
        "shape-small-light": "3.3px 3.8px 0 #6323BB",
        "shape-small-dark": "3.3px 3.8px 0 #11002C",
      },
      fontFamily: {
        sans: "SharpGrotesk",
        light20: "Light20",
        book20: "Book20",
        medium20: "Medium20",
        semibold20: "SemiBold20",
        bold20: "Bold20",
      },
      transitionProperty: {
        width0: "w-[0px]",
        width100: "w-full",
        height: "height",
        opacity: "opacity",
        display: ["visible", "invisible", "collapse", "flex", "hidden"],
      },
      animation: {
        marquee: "marquee 40s linear infinite",
        "marquee-slow": "marquee 200s linear infinite",

        "switch-right": "switch-right 0.8s ease-in-out",
        "switch-left": "switch-left 0.8s ease-in-out",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-100%)" },
        },
        "switch-right": {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(100%)" },
        },
        "switch-left": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0%)" },
        },
      },
    },
  },
  variants: {
    extend: {
      display: ["group-focus"],
      opacity: ["group-focus"],
      inset: ["group-focus"],
    },
  },
  plugins: [require("tailwindcss-animation-delay")],
};
